### PR TITLE
use RDKit's sanitize option on molecules

### PR DESCRIPTION
**Pull request by nbehrnd**
The issue of unusual valences[1] likely can be resolved for good with RDKit's optional sanitize algorithm on molecules.

[1] https://github.com/OpenChemistry/fragments/issues/13

### CODE REVIEW

**Comment by nbehrnd** [comment]
Tested with

```
Cc1cc(C)cc(c1N1CCN(C1*)c1c(C)cc(cc1C)C)C	IMes
```

now yields the anticipated

IMes

Tested with RDKit (version 2023.03.3).

**Comment by ghutchis** [comment]
I seem to remember some problem .. maybe it was with the bidentate and higher denticity? (Certainly the haptic ligands required hand-drawing in ChemDraw)

Let me think about it, but it would be great if it works .. hand-editing the SMILES is a pain.

**Comment by nbehrnd** [comment]
For the frame of the following speculation, I exclude the more complicated
ferrocene-like complexes.

By now, the dummy atom is defined in Avogadro, one draws the bond between it
an points of attachement either explicitly as single, double, triple bond, or
lets the program decide.  Possibly «any bond» and «dative» bond the .sdf
syntax permits are not implemented Avogadro's automatic assignment.

Next, if `*` shall be the symbol for the dummy atom, is its (RDKit internal)
atom number equal to 0 by call of `at.GetAtomicNum()`?  Can one use this as
placeholder for transition metal ions in an algorithm similar to the one the
RDKit's cookbook [Organometallics with Dative
Bonds](http://rdkit.org/docs/Cookbook.html#organometallics-with-dative-bonds)
around `CN(C)(C)[Pt]`?

If so, `*` takes the site of Pt; but because `*` is the unassigned, RDKit
labels the site by the dot.  Either the arrows /per sé/ to indicate the dative
character are visible, or they are invisible by the do -- at the scale of a
256x256 px preview, the difference might be little.

**Comment by nbehrnd** [comment]
An early test in the Jupyter notebook (attached in the .zip archive below) familiarizes with RDKit's example to draw dative bonds, e.g.

complex_Pt

can be extended to SMILES with a placeholder element, too:

complex_placeholder

Monodentate ligands "only" show up like the one of IMes

complex_IMes

It still would be interesting to telescope these findings into the source code of `depict-lingands.py` so the PR *should not (yet)* enter the principal branch of development.

[2023-12-05_test_dative_bonds.ipynb.zip](https://github.com/OpenChemistry/fragments/files/13572766/2023-12-05_test_dative_bonds.ipynb.zip)

**Comment by nbehrnd** [comment]
Current output of `depict-ligands.py`, an example of application with reasonable shape:

terpyridine

**Comment by ghutchis** [comment]
One thing I didn't automate is the distinction between ligands that can be generated by depict-ligands.py and those that needed manual depictions.

Maybe adding something to the groups.smi files.

**Comment by nbehrnd** [comment]
One approach plausible to me were to organize each record in the `groups.smi` in three fiels separated by a single explicit blank space:

- a logical flag, e.g.
  - `a` for script based *automatic* generation of previews
  - `m` for a *manual* generation of the previews via ChemDraw/ChemDoodle
  - `#` to skip the entry altogether, e.g. because it anyway merits some discussion
- the SMILES string
- the structure's name

as in e.g.

```
a C1=CC2=CC3[N]4C(=CC=3)C=C3[N]5=C(C=C6[N]7C(=CC1=[N]2[*]457)C=C6)C=C3 porphin
m *234[OH0]1CC[OH0]2CC[OH0]3CC[OH0]4CC1 12-crown-4
# some_SMILES_string the_corresponding_name
```

By now I know there are a few ligands with SMILES strings/dummy atom currently missing; to amend them and the adoption of this new pattern could be introduced along revising the logic in `depict-ligands.py`.  This however breaks consistency with the pattern currently used in the groups template with records consisting of SMILES string and name only; would this be acceptable?

**Comment by ghutchis** [comment]
Ah yes - EDTA was a mess from the initial RDKit depiction.

**Comment by nbehrnd** [comment]
To prevent an unnecessary increase of the binary within the git, I attach an archive *as preview* for review.  Subsequently, I intend to git rebase the edits on the group.smi into one commit in common and submit the new png.

[2023-12-07_preview.zip](https://github.com/OpenChemistry/fragments/files/13605366/2023-12-07_preview.zip)

**Comment by ghutchis** [comment]
Overall, the preview looks good. TPA looks like it might need a manual depiction. I take it that many of the tetradentate ligands still need manual depictions.

As far as git-lfs .. I think it'll depend on how often these binary files get rewritten. My guess is that they'll be pretty static so we might not need `git-lfs`. (The website, on the other hand is becoming problematic.)

**Comment by ghutchis** [comment]
@nbehrnd - do you feel this is ready to merge? It definitely looks like an improvement, particularly for new contributions.

**Comment by nbehrnd** [comment]
@ghutchis Affirmative, the improvement of the script based depiction of the ligands is the topic/feature of this branch.  The application on data available naturally closes the circle; ready to merge.

**Pull request merged**
